Create Table Job(
	JOB_CODE CHAR(3) PRIMARY KEY,
    JOB_DESCRIPTION VARCHAR(50),
    JOB_CHG_HOUR DECIMAL(5,2),
    JOB_LAST_UPDATE DATE
);

CREATE TABLE EMPLOYEE(
	EMP_NUM CHAR(3) PRIMARY KEY,
    EMP_LNAME VARCHAR(15) NOT NULL,
    EMP_FNAME VARCHAR(15) NOT NULL,
    EMP_INITIAL CHAR(1),
    EMP_HIREDATE DATE,
    JOB_CODE CHAR(3), 
    EMP_YEAR SMALLINT,
    FOREIGN KEY(JOB_CODE) REFERENCES Job(JOB_CODE)
);

Create Table Project(
PROJ_NUM CHAR(2) NOT NULL,
PROJ_NAME VARCHAR(50) NOT NULL,
PROJ_VALUE DECIMAL(12,2) NOT NULL,
PROJ_BALANCE DECIMAL(12,2) NOT NULL,
EMP_NUM CHAR (3) NOT NULL,
PRIMARY KEY (PROJ_NUM),
FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE (EMP_NUM)
);

Create Table Assignment(
	ASSIGN_NUM CHAR(4) NOT NULL,
    ASSIGN_DATE DATE NOT NULL,
    PROJ_NUM CHAR(2) NOT NULL,
    EMP_NUM CHAR (3) NOT NULL,
    ASSIGN_JOB CHAR(3) NOT NULL,
    ASSIGN_CHG_HOUR DECIMAL(5,2) NOT NULL,
    ASSIGN_HOURS DECIMAL(3,1) NOT NULL,
    PRIMARY KEY(ASSIGN_NUM),
    FOREIGN KEY(PROJ_NUM) references Project(PROJ_NUM),
    FOREIGN KEY(EMP_NUM) references EMPLOYEE (EMP_NUM)
);
#Method 1 Problem 1, Exercise 5

Select PROJ_NAME, PROJ_VALUE,PROJ_BALANCE,EMP_LNAME,EMP_FNAME,EMP_INITIAL,Job.JOB_CODE,JOB_DESCRIPTION,JOB_CHG_HOUR
From Job, EMPLOYEE, Project
Where Project.EMP_NUM = EMPLOYEE.EMP_NUM AND EMPLOYEE.JOB_CODE = Job.JOB_CODE;

# Problem 2, Exercise 5
Select EMPLOYEE.EMP_NUM, EMP_LNAME, SUM(ASSIGN_HOURS)AS SumOfASSIGN_HOURs, Sum(ASSIGN_CHG_HOUR*ASSIGN_HOURS) AS SumOfASSIGN_CHARGE
From EMPLOYEE,Assignment
Where EMPLOYEE.EMP_NUM= Assignment.EMP_NUM
group by EMPLOYEE.EMP_NUM
ORDER BY EMPLOYEE.EMP_NUM;



